### PR TITLE
support bold and italic

### PR DESCRIPTION
**Pull request by guoweilkd**

### CODE REVIEW

**Review by Miguel0101 — COMMENTED** [review]
https://github.com/lvgl/lv_lib_freetype/pull/15/files#diff-c8d4352ff3d877b785bcc767e9e8e2d34c11d291f9b57744aeb201772d23f36bR189
Don't you better rename "blod" to "bold"?

**Comment by kisvegabor** [comment]
@guoweilkd I've just merged the some 3party libs, including lv_freetype, into the main lvgl repo. 

Could you resend this PR to lvgl?

**Comment by guoweilkd** [comment]
> https://github.com/lvgl/lv_lib_freetype/pull/15/files#diff-c8d4352ff3d877b785bcc767e9e8e2d34c11d291f9b57744aeb201772d23f36bR189 Don't you better rename "blod" to "bold"?

done

**Comment by guoweilkd** [comment]
> Could you resend this PR to lvgl?

I noticed that the files in LVGL were a little different from the current one. Two different repo, how did I PR ?

**Comment by kisvegabor** [comment]
This demo shouldn't be updated as the users should use lvgl directly. 

I was thinking about archiving it should be kept alive until we need to support v8.0 (1 Jun, 2022)

**Pull request closed without merging**
